#pragma once

// Generated by manifest_tool

#include "userosc.h"

// Waveform
// Range: 0 to 2 
#define USER_PARAM__Waveform__idx k_user_osc_param_id1
#define USER_PARAM__Waveform__min 0
#define USER_PARAM__Waveform__max 2

// Decay
// Range: 0 to 100 %
#define USER_PARAM__Decay__idx k_user_osc_param_id2
#define USER_PARAM__Decay__min 0
#define USER_PARAM__Decay__max 100

// Split
// Range: -100 to 100 %
#define USER_PARAM__Split__idx k_user_osc_param_id3
#define USER_PARAM__Split__min -100
#define USER_PARAM__Split__max 100

// Tracking
// Range: 0 to 1 
#define USER_PARAM__Tracking__idx k_user_osc_param_id4
#define USER_PARAM__Tracking__min 0
#define USER_PARAM__Tracking__max 1

