#pragma once

// Generated by manifest_tool

#include "userosc.h"

// Amp dist
// Range: 0 to 100 %
#define USER_PARAM__Amp_dist__idx k_user_osc_param_id1
#define USER_PARAM__Amp_dist__min 0
#define USER_PARAM__Amp_dist__max 100

// Ph rand mod
// Range: 0 to 100 %
#define USER_PARAM__Ph_rand_mod__idx k_user_osc_param_id2
#define USER_PARAM__Ph_rand_mod__min 0
#define USER_PARAM__Ph_rand_mod__max 100

