#pragma once

// Generated by manifest_tool

#include "userosc.h"

// Attack
// Range: 0 to 100 %
#define USER_PARAM__Attack__idx k_user_osc_param_id1
#define USER_PARAM__Attack__min 0
#define USER_PARAM__Attack__max 100

// Interval
// Range: 0 to 1 
#define USER_PARAM__Interval__idx k_user_osc_param_id2
#define USER_PARAM__Interval__min 0
#define USER_PARAM__Interval__max 1

// Noise mix
// Range: 0 to 100 %
#define USER_PARAM__Noise_mix__idx k_user_osc_param_id3
#define USER_PARAM__Noise_mix__min 0
#define USER_PARAM__Noise_mix__max 100

// Decay
// Range: 0 to 100 %
#define USER_PARAM__Decay__idx k_user_osc_param_id4
#define USER_PARAM__Decay__min 0
#define USER_PARAM__Decay__max 100

