#pragma once

// Generated by manifest_tool

#include "userosc.h"

// LFO Int
// Range: 0 to 100 %
#define USER_PARAM__LFO_Int__idx k_user_osc_param_id1
#define USER_PARAM__LFO_Int__min 0
#define USER_PARAM__LFO_Int__max 100

// LFO Freq
// Range: 0 to 100 %
#define USER_PARAM__LFO_Freq__idx k_user_osc_param_id2
#define USER_PARAM__LFO_Freq__min 0
#define USER_PARAM__LFO_Freq__max 100

// LFO Target
// Range: 0 to 6 
#define USER_PARAM__LFO_Target__idx k_user_osc_param_id3
#define USER_PARAM__LFO_Target__min 0
#define USER_PARAM__LFO_Target__max 6

// Sticky
// Range: 0 to 100 
#define USER_PARAM__Sticky__idx k_user_osc_param_id4
#define USER_PARAM__Sticky__min 0
#define USER_PARAM__Sticky__max 100

// Position
// Range: 0 to 100 %
#define USER_PARAM__Position__idx k_user_osc_param_id5
#define USER_PARAM__Position__min 0
#define USER_PARAM__Position__max 100

// Order
// Range: 0 to 19 
#define USER_PARAM__Order__idx k_user_osc_param_id6
#define USER_PARAM__Order__min 0
#define USER_PARAM__Order__max 19

