#pragma once

// Generated by manifest_tool

#include "userosc.h"

// Synth var
// Range: 0 to 31 
#define USER_PARAM__Synth_var__idx k_user_osc_param_id1
#define USER_PARAM__Synth_var__min 0
#define USER_PARAM__Synth_var__max 31

// Kick cut
// Range: 0 to 100 %
#define USER_PARAM__Kick_cut__idx k_user_osc_param_id2
#define USER_PARAM__Kick_cut__min 0
#define USER_PARAM__Kick_cut__max 100

// Snare cut
// Range: 0 to 100 %
#define USER_PARAM__Snare_cut__idx k_user_osc_param_id3
#define USER_PARAM__Snare_cut__min 0
#define USER_PARAM__Snare_cut__max 100

// Hats cut
// Range: 0 to 100 %
#define USER_PARAM__Hats_cut__idx k_user_osc_param_id4
#define USER_PARAM__Hats_cut__min 0
#define USER_PARAM__Hats_cut__max 100

// Crash cut
// Range: 0 to 100 %
#define USER_PARAM__Crash_cut__idx k_user_osc_param_id5
#define USER_PARAM__Crash_cut__min 0
#define USER_PARAM__Crash_cut__max 100

// Perc cut
// Range: 0 to 100 %
#define USER_PARAM__Perc_cut__idx k_user_osc_param_id6
#define USER_PARAM__Perc_cut__min 0
#define USER_PARAM__Perc_cut__max 100

