#!/usr/bin/python3

import json
import argparse
from dataclasses import dataclass
import re

@dataclass
class Param:
    name: str
    range_min: int
    range_max: int
    unit: str

parser = argparse.ArgumentParser()

parser.add_argument('manifest')
parser.add_argument('-g', '--get', default='')
parser.add_argument('-u', '--update-with', default=None)
parser.add_argument('-v', '--set-version', default='')
parser.add_argument('-d', '--dry-run', action='store_true')
parser.add_argument('-V', '--verify', action='store_true')
parser.add_argument('-p', '--generate-params-header', default='')
parser.add_argument('-i', '--info', action='store_true')

args = parser.parse_args()

modified = False

with open(args.manifest) as f:
    manifest = json.load(f)

def verify_manifest():
    assert manifest['header']['platform'] == 'minilogue-xd'
    assert manifest['header']['api'] == '1.1-0'
    assert manifest['header']['dev_id'] == 0
    assert manifest['header']['prg_id'] == 0
    assert re.match(r'^\d+\.\d+\-\d+$', manifest['header']['version'])
    assert len(manifest['header']['name']) > 0
    assert manifest['header']['module'] in ['osc', 'modfx', 'delfx', 'revfx']
    if manifest['header']['module'] == 'osc':
        assert len(manifest['header']['params']) == manifest['header']['num_param']
        for p in manifest['header']['params']:
            param = Param(*p)
    else:
        assert manifest['header']['num_param'] == 0
        assert 'params' not in manifest['header']

if args.verify:
    verify_manifest()

if args.get:
    print(manifest['header'][args.get])
    if args.update_with is not None:
        modified = True
        manifest['header'][args.get] = args.update_with
        verify_manifest()

if args.set_version:
    modified = True
    manifest['header']['version'] = args.set_version
    verify_manifest()

if args.generate_params_header and manifest['header']['module'] == 'osc':
    lines = ['#pragma once', '\n// Generated by manifest_tool\n', '#include "userosc.h"\n']
    for i, p in enumerate(manifest['header']['params']):
        param = Param(*p)
        macro_name = re.sub('[^a-zA-Z_0-9]', lambda mo: f'_sym{mo.group(0).encode()[0]}_', param.name.replace(' ', '_'))
        macro_name = 'USER_PARAM__' + macro_name
        lines.append(f'// {param.name}')
        lines.append(f'// Range: {param.range_min} to {param.range_max} {param.unit}')
        lines.append(f'#define {macro_name}__idx k_user_osc_param_id{i + 1}')
        lines.append(f'#define {macro_name}__min {param.range_min}')
        lines.append(f'#define {macro_name}__max {param.range_max}\n')
    with open(args.generate_params_header, 'w') as f:
        f.write('\n'.join(lines) + '\n')
        
if modified and args.dry_run:
    print(json.dumps(manifest, indent=4))
elif modified:
    with open(args.manifest, 'w') as f:
        json.dump(manifest, f, indent=4)

