#pragma once

// Generated by manifest_tool

#include "userosc.h"

// O1 Waveform
// Range: 0 to 4 
#define USER_PARAM__O1_Waveform__idx k_user_osc_param_id1
#define USER_PARAM__O1_Waveform__min 0
#define USER_PARAM__O1_Waveform__max 4

// O1 Atten
// Range: 0 to 100 %
#define USER_PARAM__O1_Atten__idx k_user_osc_param_id2
#define USER_PARAM__O1_Atten__min 0
#define USER_PARAM__O1_Atten__max 100

// O2 Mix
// Range: 0 to 100 %
#define USER_PARAM__O2_Mix__idx k_user_osc_param_id3
#define USER_PARAM__O2_Mix__min 0
#define USER_PARAM__O2_Mix__max 100

// O2 Waveform
// Range: 0 to 4 
#define USER_PARAM__O2_Waveform__idx k_user_osc_param_id4
#define USER_PARAM__O2_Waveform__min 0
#define USER_PARAM__O2_Waveform__max 4

// O2 Octave
// Range: 0 to 4 
#define USER_PARAM__O2_Octave__idx k_user_osc_param_id5
#define USER_PARAM__O2_Octave__min 0
#define USER_PARAM__O2_Octave__max 4

// O2 Detune
// Range: 0 to 99 %
#define USER_PARAM__O2_Detune__idx k_user_osc_param_id6
#define USER_PARAM__O2_Detune__min 0
#define USER_PARAM__O2_Detune__max 99

