#pragma once

// Generated by manifest_tool

#include "userosc.h"

// Osc1 mix
// Range: 0 to 100 %
#define USER_PARAM__Osc1_mix__idx k_user_osc_param_id1
#define USER_PARAM__Osc1_mix__min 0
#define USER_PARAM__Osc1_mix__max 100

// Osc2 mix
// Range: 0 to 100 %
#define USER_PARAM__Osc2_mix__idx k_user_osc_param_id2
#define USER_PARAM__Osc2_mix__min 0
#define USER_PARAM__Osc2_mix__max 100

